name: setup-playwright
description: 🚙 reuse playwright setup on CI over and over

runs:
  using: composite
  steps:
    - run: npx playwright install --with-deps
    - run: pnpm t
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
